#!/bin/sh

# Make the mouse visible
xsetroot -cursor_name left_ptr

## Wallpaper setting
pkill xwinwrap | pkill hsetroot | pkill sxiv

# Image
hsetroot -cover ~/Images/Walls/1.jpg

# Animated background
#xwinwrap -ov -ni -fs -- mpv -vo x11 -wid WID --keepaspect=no --pause=no --loop ~/Images/Wallpapers/*.gif &
#xwinwrap -ov -ni -fs -- sxiv -a -e WID -f -b -g 1366x768  ~/Images/Wallpapers/*.gif &

# Polybar
pkill polybar
polybar example & disown

# Compositor
pkill picom
#picom -b &

# Default prefered settings
amixer -q set Master 100% &
xbacklight -set 60 &

# Set decoration geometry
berryc border_width       3
berryc inner_border_width 3
berryc title_height       0
berryc top_gap            0

# Set decoration colors
berryc focus_color         455173
berryc unfocus_color       161623
berryc inner_focus_color   7D97B8
berryc inner_unfocus_color 7D97B8 
berryc text_focus_color    9BB3DC 
berryc text_unfocus_color  A6BBD9

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"
berryc set_font "kakwafont-10"
