#!/bin/bash

# Wallpaper settings
hsetroot --fill '/home/lyes/Images/Wallpaper/Wallpaper.jpg' &

# Set decoration geometry
berryc border_width       3
berryc inner_border_width 3
berryc title_height       0
berryc top_gap            18

# Set decoration colors
berryc focus_color         A3BE8C
berryc unfocus_color       ECEFF4
berryc inner_focus_color   FFCB6B
berryc inner_unfocus_color 81A1C1
berryc text_focus_color    8FBCBB
berryc text_unfocus_color  eeeeee

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"
berryc set_font "cherry-10"
